language: python

matrix:
    include:
        - os: linux
          sudo: false
          python: 2.7
        - os: linux
          sudo: false
          python: 3.4
        - os: linux
          sudo: false
          python: 3.5
#        - os: osx
#          language: generic
#          env:
#              - TRAVIS_OSX_PYTHON_VERSION=py35
#              - TRAVIS_PYTHON_VERSION=3.5.1

cache:
 directories:
  - $HOME/misc_cache
  - $HOME/virtualenv
  - $HOME/miniconda

env:
  global:
  - CACHE_DIR="$HOME/misc_cache"
  - MINICONDA_DIR="$HOME/miniconda"
  - PIP_DIR="$HOME/virtualenv"
  - GATK_PATH="$CACHE_DIR/GenomeAnalysisTK-3.6"
  - PYTHONIOENCODING=UTF8
  - secure: KX7DwKRD85S7NgspxevgbulTtV+jHQIiM6NBus2/Ur/P0RMdpt0EQQ2wDq79qGN70bvvkw901N7EjSYd+GWCAM7StXtaxnLRrrZ3XI1gX7KMk8E3QzPf0zualLDs7cuQmL6l6WiElUAEqumLc7WGpLZZLdSPzNqFSg+CBKCmTI8=

git:
  depth: 3

before_install:
  - travis/before_install.sh

install:
  - source travis/install-conda.sh
  - source travis/install-tools.sh
  - travis/install-pip.sh

script:
  - travis/tests-unit.sh
  - travis/tests-long.sh

after_success:
  - coveralls
